// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCj1nJx__A2Jzj0ye8KgYrd8UH9utoy4M',
    appId: '1:370173827349:android:2d314ca1ebd45eee71711c',
    messagingSenderId: '370173827349',
    projectId: 'fir-sample-c4bfe',
    storageBucket: 'fir-sample-c4bfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj9ZrmTtsLATBLNWzcpEB9Uu10CDChjMo',
    appId: '1:370173827349:ios:c19f65a12fc2819071711c',
    messagingSenderId: '370173827349',
    projectId: 'fir-sample-c4bfe',
    storageBucket: 'fir-sample-c4bfe.appspot.com',
    androidClientId: '370173827349-f3c48k38rr204jp0o50o3t00dtm3b4ls.apps.googleusercontent.com',
    iosClientId: '370173827349-2o2980j3afl43g6b5gllvu91oi6b6k6g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseSample',
  );
}
